### ISSUE TITLE
authority/host could not be parsed

### ISSUE THREAD

**Issue by jeromecc** [robinmalburn/keepass-diceware-generator#7]
Hello!

On KeePass 2.47.

When generation is launched, this pop up show up:

"Failed to generate a password"
"Invalid URI: the Authority/Host coud not be parsed"

Thanks.

**Comment by robinmalburn** [comment]
Hey there, thanks for the bug report, sorry you've ran into an issue. 

That error sounds like it's failed to locate/read one of the Diceware text files it needs to read when generating the password, so could  double check that the files are located in the Plugins folder mentioned in the [readme](https://github.com/robinmalburn/keepass-diceware-generator#installation)?

The other bit that jumps out at me is; could you let me know what OS you're on?  I know the way the Assembly reports the file path differs wildly between operating systems, and I've been able to test it _fairly_ thoroughly on windows, but far less so on Mac/Linux, so if you're on one of those, it's possible that we're running afoul of some dodgy research into the way paths are returned on different OSes that I can fix up.

**Comment by jeromecc** [comment]
The three text files are inside the ../KeePass-2.47/Plugins/Diceware subfolder. Other plugins are working well.

My OS is Debian 10 Buster 64 bits (x86-64).

Hope it helps. I have zero knowledge of C# and Mono unfortunately...

**Comment by jeromecc** [comment]
All other KeePass plugins have a xxx.plgx file along with the xxx.dll file. Is it a requirement or optional? There was only a dll file inside the zip of your release if I'm not mistaken.

**Comment by robinmalburn** [comment]
Thanks for the extra info, it’s much appreciated.  

The .plgx files you mentioned are an alternate format for plugins that KeePass makes available which I’m not currently using, so no problem with those being missing, that’s all good.

It sounds most likely it’s how Debian is reporting the path to the assembly, so I’ll spin up a virtual machine to debug that & hopefully that’ll sort things.

**Comment by robinmalburn** [comment]
@jeromecc That should be fixed in patch 0.4.1 now - annoying little issue with the way URIs are returned.  They're not particularly well handled between windows or Linux, but on Linux the language decides to throw an exception, whereas in Windows it decides to just merrily carry on and cope.  I've added better handling for that now and tested it in an Ubuntu virtual machine and all seems good.

I've done this as a 0.4.1 patch release, but hoping to have a fairly significant 1.0 update coming soon that largely just tidies up the code base and adds a lot more testing and simplifications, but wanted to get this patch out quick so it wasn't holding up usage.
